src: Add functions for EC2
dxdc/aws-sdk-google-apps pull request #10
Opened 2022-11-02 06:39 UTC by AbdealiJK

Add some functinos to interface with AWS EC2 apis (EC2 instances and security groups)
Also add it in Examples.js with some tests

Finally update the documentation to mention that EC2 will be included by default

Fixes https://github.com/dxdc/aws-sdk-google-apps/issues/9

2022-11-02 09:20 UTC, dxdc requested changes
Thanks for the PR @AbdealiJK! I've added some minor comments. In addition to some tweaks to the documentation, I didn't understand the purpose of returning an object instead of just an array for your test methods. I think it's cleaner just to return an array.

Also, `.npmrc` needs to be updated to include `ec2` in the default build.

2022-11-02 09:20 UTC, dxdc commented on README.md
> +2. Initialize your AWS config settings and implement one of this library's [S3](dist/S3.js), [Lambda](dist/Lambda.js), [SES](dist/Ses.js), [EC2](dist/EC2.js) functions. [Examples.js](dist/Examples.js
```suggestion
2. Initialize your AWS config settings and implement one of this library's [S3](dist/S3.js), [Lambda](dist/Lambda.js), [SES](dist/Ses.js), or [EC2](dist/EC2.js) functions. [Examples.js](dist/Examples.js) shows some working examples.
```

2022-11-02 09:20 UTC, dxdc commented on README.md
> +3. Methods for common S3, Lambda, SES services, and EC2 services have been implemented. However, direct access to library AWS SDK methods is also available via the `AWS` property on your chosen libra
```suggestion
3. Methods for common S3, Lambda, SES, and EC2 services have been implemented. However, direct access to library AWS SDK methods is also available via the `AWS` property on your chosen library identifier, e.g.:
```

2022-11-02 09:20 UTC, dxdc commented on README.md
> +This project defaults to the following services: `ses,s3,lambda,ec2`.
In this case `.npmrc` needs to be modified to add ec2 to the default list of services.

2022-11-02 09:20 UTC, dxdc commented on src/Examples.js
> +  return { instances: instances };
```suggestion
  return instances;
```

2022-11-02 09:20 UTC, dxdc commented on src/Examples.js
> +  return { groups: groups };
```suggestion
  return groups;
```

2022-11-03 21:53 UTC, AbdealiJK commented
Makes sense - thanks for the feedback - I have incorporated them and ammended my commit

2022-11-03 22:41 UTC, dxdc approved these changes

2022-11-03 22:41 UTC, merged

2022-11-03 22:49 UTC, dxdc commented
thanks for your contribution @AbdealiJK! I re-built with the latest SDK and the library is now live with your changes.